config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
  end
  resources :friends
  get 'home/index'
  get 'home/about'
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  
  def about
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    protected
  
    def after_sign_up_path_for(resource)
      '/' # Or :prefix_to_your_route
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<div class="bg-dark text-white border border-dark rounded-3 fs-5 p-4 col-8">
  <%= form_with(model: friend) do |form| %>
    <% if friend.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

        <ul>
          <% friend.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="row">
      <div class="mb-3 col-4">
        <%= form.label :first_name, class:"form-label" %>
        <%= form.text_field :first_name, class:"form-control" %>
      </div>

      <div class="mb-3 col-4">
        <%= form.label :last_name, class:"form-label" %>
        <%= form.text_field :last_name, class:"form-control" %>
      </div>
    </div>
    <div class="mb-3 col-8">
      <%= form.label :email, class:"form-label" %>
      <%= form.text_field :email, class:"form-control" %>
    </div>
    <div class="row">
      <div class="mb-3 col-4">
        <%= form.label :phone, class:"form-label" %>
        <%= form.text_field :phone, class:"form-control" %>
      </div>

      <div class="mb-3 col-4">
        <%= form.label :twitter, class:"form-label" %>
        <%= form.text_field :twitter, class:"form-control" %>
      </div>
    </div>
    <div>
      <%= form.submit class: "btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>">
  <p>
    <strong>First name:</strong>
    <%= friend.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= friend.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= friend.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= friend.phone %>
  </p>

  <p>
    <strong>Twitter:</strong>
    <%= friend.twitter %>
  </p>

</div>

app/views/friends/edit.html.erb
<h1>Editing friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Go Back", @friend , class: "btn btn-primary" %>
</div>

app/views/friends/index.html.erb
<h1>Friends List</h1>
<table class="table table-dark table-hover table-bordered">
  <thead class="">
    <tr>
      <th scope="col">#</th>
      <th scope="col">First</th>
      <th scope="col">Last</th>
      <th scope="col">Email</th>
      <th scope="col">Phone</th>
      <th scope="col">Twitter</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% i=0 %> 
    <% @friends.each do |friend| %>
      <% i += 1 %> 
      <tr>
        <td><%= i %></td>
        <td><%= friend.first_name %></td>
        <td><%= friend.last_name %></td>
        <td><%= friend.email %></td>
        <td><%= friend.phone %></td>
        <td><%= friend.twitter %></td>
        <td><%= link_to "Show Details", friend, class: "btn btn-info btn-sm" %></td>
      </tr>
    <% end %>  
  </tbody>
</table>


<%= link_to "Add New Friend", new_friend_path, class: "btn btn-primary" %>

app/views/friends/new.html.erb
<h1>Add New friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Go Back", friends_path, class: "btn btn-primary" %>
</div>

app/views/friends/show.html.erb
<div class="container bg-dark text-white border border-dark p-3 rounded-3" >
  <div class="container border-bottom">
    <h1 class="display-1"><%= @friend.first_name %> <%= @friend.last_name %>  </h1>
  </div>
  <div class="container mt-4 fs-3 fw-light">
    <%= @friend.email %> | +91 <%= @friend.phone %> | <%= @friend.twitter %>
  </div>
  <div class="container mt-4">
    <%= link_to "Edit", edit_friend_path(@friend), class: "btn btn-outline-light" %> <%= link_to "Go Back", friends_path, class: "btn btn-outline-light ms-3" %>
  </div>
  <div class="container mt-4">
    <%= button_to "Delete", @friend, method: :delete, class: "btn btn-danger" %>
  </div>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'FRIENDS', root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
        <!-- <%= link_to 'Home', home_index_path, class: "nav-link" %> -->
        <%= link_to 'Friends List', friends_path, class: "nav-link" %>
        <% if user_signed_in? then %>
          <%= link_to 'Add Friend', new_friend_path, class: "nav-link" %>
        <% end %> 
        <%= link_to 'About Us', home_about_path, class: "nav-link" %>
      </div>
      <div class="navbar-nav ms-auto">
        <% if user_signed_in? then %>
          <%= link_to 'Edit Profile', edit_user_registration_path, class: "nav-link" %>
          <%= link_to "Logout", destroy_user_session_path, :method => :delete, class: "nav-link" %>
        <% else %> 
          <%= link_to 'Sign Up', new_user_registration_path, class: "nav-link" %>
          <%= link_to 'Sign In', new_user_session_path, class: "nav-link" %>
        <% end %>  
      </div>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About Us</h1>
<p>This is the about page.</p>

app/views/home/index.html.erb
<h1>Hello Rails!</h1>
<p>This is my first rails webpage.</p>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show mt-2" role="alert">
  <%= notice %> 
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Friends App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body class="">
    <%= render "home/header" %> 
    <div class="container mt-3">
      <% if notice %> 
        <%= render "layouts/alerts" %> 
      <% end %>
      <%= yield %>
    </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>